project:
  name: cfn-abi-lacework-polygraph
  owner: jeff.fry@lacework.net
  package_lambda: true
  regions:
  - ap-northeast-1
  - ap-northeast-2
  - ap-southeast-1
  - ap-southeast-2
  - eu-central-1
  - eu-west-1
  - sa-east-1
  - us-east-1
  - us-west-1
  - us-west-2
tests:
  cfn-abi-lacework-polygraph-multi-org-multi-sub-mapping:
    regions:
      - us-east-1  # Control Tower Home region for Pilot
  template: templates/cfn-abi-lacework-polygraph.template.yml
  parameters:
      pSRASourceS3BucketName: $[taskcat_autobucket]
      pSRAS3BucketRegion: us-east-1  # Bucket region. Keep it to us-east-1 as all the resources are deployed in the region.
      LaceworkURL: $[taskcat_secretsmanager_laceworkurl]
      LaceworkAccessKeyID: $[taskcat_secretsmanager_laceworkaccesskeyid]
      LaceworkSecretKey: $[taskcat_secretsmanager_laceworksecretkey]
      LaceworkOrgSubAccountNames: $[taskcat_secretsmanager_laceworkorgsubaccountnames]