project_id: 'abip-1kirFQBF75MfEQ3RbMQHRb-1uUqxTu50BQyeDu1QxxGqM-ln893493'
project_name: 'ABI Lacework Polygraph'
project_code: '313cd725-d4b4-426e-80cd-c49205bde6ec'
project_type: 'ABI CloudFormation Project Type'
partner_name: 'Lacework'
launch_date: '2023-10-04'
repo_name: 'cfn-abi-lacework-polygraph'
templates_info:
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-1uUqxTu50BQyeDu1QxxGqM-ln8935st'
    file_name: 'templates/cfn-abi-lacework-polygraph.template.yaml'
    count_flag: 'true'
  - template_id: 'abi-1kirFQBF75MfEQ3RbMQHRb-1uUqxTu50BQyeDu1QxxGqM-ln89350v'
    file_name: 'templates/cfn-abi-lacework-sec-hub-ingest.template.yaml'
    count_flag: 'false'