AWSTemplateFormatVersion: 2010-09-09
Description: "AWS Built-in package with Lacework. Bundled AWS Control Tower, Amazon GuardDuty, AWS Security Hub and Lacework. (abp-1kirFQBF75MfEQ3RbMQHRb-1uUqxTu50BQyeDu1QxxGqM-ln8935st)"
Metadata:
  AWS::CloudFormation::Interface:
    ParameterGroups:
      - Label:
          default: General Properties
          Parameters:
            - pSRASourceS3BucketName
            - pSRAStagingS3KeyPrefix
            - pSRAS3BucketRegion
            - pSRAAlarmEmail
            - pRepoURL
            - pRepoBranch
      - Label:
          default: "Lacework Configuration Properties"
        Parameters:
          - LaceworkURL
          - LaceworkAccessKeyID
          - LaceworkSecretKey
          - CapabilityType
          - ExistingAccounts
          - ExistingCloudTrail
          - KMSKeyIdentifierARN
          - LogAccountName
          - AuditAccountName
      - Label:
          default: "Organization Configuration (Optional)"
        Parameters:
          - LaceworkOrgSubAccountNames
      - Label:
          default: "Single Sub-Account Configuration (Optional)"
        Parameters:
          - LaceworkSubAccountName
      - Label:
          default: Security Hub Configuration Properties
        Parameters:
          - pDisableSecurityHub
          - pEnableSecurityBestPracticesStandard
          - pEnableCISStandard
          - pCISStandardVersion
          - pEnablePCIStandard
          - pRegionLinkingMode
      - Label:
          default: GuardDuty Configuration Properties
        Parameters:
          - pDisableGuardDuty
          - pAutoEnableS3Logs
          - pAutoEnableKubernetesAuditLogs
          - pAutoEnableMalwareProtection
          - pEnableRdsLoginEvents
          - pEnableEksRuntimeMonitoring
          - pEnableEksAddonManagement
          - pEnableLambdaNetworkLogs
          - pGuardDutyFindingPublishingFrequency
      - Label:
          default: General Lambda Function Properties
        Parameters:
          - pCreateLambdaLogGroup
          - pLambdaLogGroupRetention
          - pLambdaLogGroupKmsKey
          - pLambdaLogLevel

      - Label:
          default: EventBridge Rule Properties
        Parameters:
          - pComplianceFrequency

    ParameterLabels:
      # General Properties
      pSRASourceS3BucketName:
        default: SRA Source S3 Location
      pSRAStagingS3KeyPrefix:
        default: SRA Source Key
      pSRAS3BucketRegion:
        default: SRA Bucket Region
      pSRAAlarmEmail:
        default: (Optional) SRA Alarm Email
      pRepoURL:
        default: URL of the AWS SRA Repository
      pRepoBranch:
        default: A tag version to use with in the SRA repository
      # Lacework Configuration Properties
      LaceworkURL:
        default: Your Lacework URL
      LaceworkOrgSubAccountNames:
        default: AWS Organizations to Lacework Sub-Account Names
      LaceworkSubAccountName:
        default: Lacework Sub-Account Name
      LaceworkAccessKeyID:
        default: Lacework Access Key ID
      LaceworkSecretKey:
        default: Lacework Secret Key
      CapabilityType:
        default: Capability Type
      ExistingAccounts:
        default: Monitor Existing Accounts
      ExistingCloudTrail:
        default: Existing AWS Control Tower CloudTrail Name
      LogAccountName:
        default: Log Account Name
      AuditAccountName:
        default: Audit Account Name
      KMSKeyIdentifierARN:
        default: KMS Key Identifier ARN for CloudTrail S3 Logs Decrypt
      # Security Hub Configuration Properties
      pDisableSecurityHub:
        default: Disable Security Hub
      pEnableSecurityBestPracticesStandard:
        default: Enable AWS Foundational Security Best Practices Standard
      pEnableCISStandard:
        default: Enable CIS Standard
      pCISStandardVersion:
        default: CIS Standard Version
      pEnablePCIStandard:
        default: Enable PCI Standard
      pRegionLinkingMode:
        default: Region Linking Mode
      # GuardDuty Configuration Properties
      pDisableGuardDuty:
        default: Disable GuardDuty in all accounts and regions before deleting the stack
      pAutoEnableS3Logs:
        default: Auto Enable S3 Logs
      pAutoEnableKubernetesAuditLogs:
        default: Auto Enable kubernetes Logs
      pAutoEnableMalwareProtection:
        default: Auto Enable malware protection
      pEnableRdsLoginEvents:
        default: Auto Enable RDS Login Events
      pEnableEksRuntimeMonitoring:
        default: Auto Enable EKS Runtime Monitoring
      pEnableEksAddonManagement:
        default: Auto enable EKS Add-on Management
      pEnableLambdaNetworkLogs:
        default: Auto enable Lambda Network Logs
      pGuardDutyFindingPublishingFrequency:
        default: Finding publishing frequency
      # General Lambda Function Properties
      pCreateLambdaLogGroup:
        default: Create Lambda Log Group
      pLambdaLogGroupRetention:
        default: Lambda Log Group Retention
      pLambdaLogGroupKmsKey:
        default: (Optional) Lambda Logs KMS Key
      pLambdaLogLevel:
        default: Lambda Log Level
      # EventBridge Rule Properties
      pComplianceFrequency:
        default: Frequency to Check for Organizational Compliance
Parameters:
  # General Properties
  pSRASourceS3BucketName:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Type: String
    Default: aws-abi
  pSRAStagingS3KeyPrefix:
    AllowedPattern: ^[0-9a-zA-Z]+([0-9a-zA-Z-]*[0-9a-zA-Z])*$
    Type: String
    Default: cfn-abi-lacework-polygraph
  pSRAS3BucketRegion:
    AllowedPattern: ^[a-z][a-z]-[a-z]*-[0-9]*$
    Type: String
    Default: us-east-1
  pSRAAlarmEmail:
    AllowedPattern: '^$|^([a-zA-Z0-9_.+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-.]+)$'
    ConstraintDescription: Must be a valid email address.
    Default: ''
    Description: (Optional) Email address for receiving SRA alarms
    Type: String
  pRepoURL:
    Default: "https://github.com/aws-samples/aws-security-reference-architecture-examples.git"
    Description: AWS Security Reference Architecture examples repository URL
    Type: String
  pRepoBranch:
    Default: "tags/v3.0.4"
    Description: SRA version to tag
    Type: String
  # lacework parameters
  LaceworkURL:
    Type: String
    Description: "Enter your Lacework URL. ie. account.lacework.net."
    MinLength: '1'
    AllowedPattern: '(.+?)\.lacework\.net'
    ConstraintDescription: "Invalid Lacework URL."
  LaceworkOrgSubAccountNames:
    Type: String
    Description: "Use for AWS organizations to Lacework sub-accounts mapping. Provide a commas-separated list. Leave blank otherwise. If used, ensure that the Lacework credentials are for the Organization Admin."
    AllowedPattern: '^$|^[a-zA-Z0-9.,]+(?:-[a-zA-Z0-9.,]+)*$'
    ConstraintDescription: "Invalid list entered. The sub-account name may contain alphanumeric characters and dashes only."
    Default: ''
  LaceworkSubAccountName:
    Type: String
    Description: "Use for a single sub-account use only. Leave blank otherwise. If used, ensure that the Lacework credentials are for the Sub-Account."
    AllowedPattern: '^$|^[a-zA-Z0-9.]+(?:-[a-zA-Z0-9.]+)*$'
    ConstraintDescription: "Invalid Lacework account name entered. The account name may contain alphanumeric characters and dashes only."
    Default: ''
  LaceworkAccessKeyID:
    Type: String
    MinLength: '1'
    AllowedPattern: '^[-a-zA-Z0-9_]*$'
    ConstraintDescription: "The Lacework API Access Key ID contains alphanumeric characters and symbols only."
    Description: "Enter the Lacework API Secret Key ID. See https://support.lacework.com/hc/en-us/articles/360011403853-Generate-API-Access-Keys-and-Tokens."
  LaceworkSecretKey:
    Type: String
    NoEcho: true
    MinLength: '1'
    AllowedPattern: '^[a-zA-Z0-9_]*$'
    ConstraintDescription: "The Lacework API Secret Key contains alphanumeric characters and symbols only."
    Description: "Enter the Lacework API Secret Key. See https://support.lacework.com/hc/en-us/articles/360011403853-Generate-API-Access-Keys-and-Tokens."
  CapabilityType:
    AllowedValues:
      - 'CloudTrail+Config'
      - 'Config'
    Type: String
    Default: CloudTrail+Config
    Description: "Enter the Lacework Control Tower StackSet type to use."
  ExistingAccounts:
    Description: "Choose to monitor any existing accounts. SUSPENDED accounts are skipped."
    Type: String
    AllowedValues:
      - 'Yes'
      - 'No'
    Default: 'Yes'
  ExistingCloudTrail:
    Type: String
    MinLength: '1'
    AllowedPattern: '^[-a-zA-Z0-9_]*$'
    ConstraintDescription: "Invalid CloudTrail name."
    Description: "Enter your existing AWS Control Tower CloudTrail name."
    Default: 'aws-controltower-BaselineCloudTrail'
  LogAccountName:
    Type: String
    Description: "Enter your AWS Control Tower log account name."
    MinLength: '1'
    AllowedPattern: '^[-a-zA-Z0-9\s]*$'
    ConstraintDescription: "The account name contains alphanumeric characters only."
    Default: "Log Archive"
  AuditAccountName:
    Type: String
    Description: "Enter your AWS Control Tower audit account name."
    MinLength: '1'
    AllowedPattern: '^[-a-zA-Z0-9\s]*$'
    ConstraintDescription: "The account name contains alphanumeric characters only."
    Default: "Audit"
  KMSKeyIdentifierARN:
    Description: "Provide the ARN of the KMS key for decrypting S3 log files decryption if necessary. Ensure that the Lacework account or role has kms:decrypt access within the Key Policy. Won't use KMS decrypt if no key provided."
    Default: ''
    Type: String
    MaxLength: '256'
  # SecurityHub Configuration Properties
  pDisableSecurityHub:
    AllowedValues: ['Yes', 'No']
    Default: 'No'
    Description: Update to 'Yes' to disable Security Hub in all accounts and regions before deleting the stack.
    Type: String
  pEnableSecurityBestPracticesStandard:
    AllowedValues: [ 'true', 'false' ]
    Default: 'true'
    Description: Indicates whether to enable the AWS Foundational Security Best Practices Standard.
    Type: String
  pEnableCISStandard:
    AllowedValues: [ 'true', 'false' ]
    Default: 'false'
    Description: Indicates whether to enable the CIS AWS Foundations Benchmark Standard.
    Type: String
  pCISStandardVersion:
    AllowedValues: [ 1.2.0, 1.4.0 ]
    Default: 1.4.0
    Description: CIS Standard Version
    Type: String
  pEnablePCIStandard:
    AllowedValues: [ 'true', 'false' ]
    Default: 'false'
    Description: Indicates whether to enable the Payment Card Industry Data Security Standard (PCI DSS).
    Type: String
  pRegionLinkingMode:
    AllowedValues: [ SPECIFIED_REGIONS, ALL_REGIONS ]
    Default: SPECIFIED_REGIONS
    Description:
      Indicates whether to aggregate findings from all of the available Regions in the current partition. Also determines whether to automatically
      aggregate findings from new Regions as Security Hub supports them and you opt into them.
    Type: String
  # GuardDuty Configuration Properties
  pDisableGuardDuty:
    AllowedValues: ['Yes', 'No']
    Default: 'No'
    Description: Disable the GuardDuty solution in all accounts and regions before deleting the stack.
    Type: String
  pAutoEnableS3Logs:
    AllowedValues: [ 'true', 'false' ]
    Default: 'true'
    Description: Auto enable S3 logs
    Type: String
  pAutoEnableKubernetesAuditLogs:
    AllowedValues: [ 'true', 'false' ]
    Default: 'false'
    Description: Auto Enable kubernetes Logs
    Type: String
  pAutoEnableMalwareProtection:
    AllowedValues: [ 'true', 'false' ]
    Default: 'false'
    Description: Auto Enable malware protection
    Type: String
  pEnableRdsLoginEvents:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Auto enable RDS Login Events
    Type: String
  pEnableEksRuntimeMonitoring:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Auto enable EKS Runtime Monitoring
    Type: String   
  pEnableEksAddonManagement:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Auto enable EKS Add-on Management
    Type: String
  pEnableLambdaNetworkLogs:
    AllowedValues: ['true', 'false']
    Default: 'true'
    Description: Auto enable Lambda Network Logs
    Type: String
  pGuardDutyFindingPublishingFrequency:
    AllowedValues: [FIFTEEN_MINUTES, ONE_HOUR, SIX_HOURS]
    Default: FIFTEEN_MINUTES
    Description: Finding publishing frequency
    Type: String 
  # General Lambda Function Properties
  pCreateLambdaLogGroup:
    AllowedValues: ['Yes', 'No']
    Default: 'No'
    Description:
      Indicates whether a CloudWatch Log Group should be explicitly created for the Lambda function, to allow for setting a Log Retention and/or KMS
      Key for encryption.
    Type: String
  pLambdaLogGroupRetention:
    AllowedValues: [ 1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653 ]
    Default: 14
    Description: Specifies the number of days you want to retain log events
    Type: String
  pLambdaLogGroupKmsKey:
    AllowedPattern: '^$|^arn:(aws[a-zA-Z-]*){1}:kms:[a-z0-9-]+:\d{12}:key\/[a-f0-9]{8}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{4}-[a-f0-9]{12}$'
    ConstraintDescription: 'Key ARN example:  arn:aws:kms:us-east-2:111122223333:key/1234abcd-12ab-34cd-56ef-1234567890ab'
    Default: ''
    Description:
      (Optional) KMS Key ARN to use for encrypting the Lambda logs data. If empty, encryption is enabled with CloudWatch Logs managing the server-side
      encryption keys.
    Type: String
  pLambdaLogLevel:
    AllowedValues: [ INFO, ERROR, DEBUG ]
    Default: INFO
    Description: Lambda Function Logging Level
    Type: String
  # EventBridge Rule Properties
  pComplianceFrequency:
    ConstraintDescription: Compliance Frequency must be a number between 1 and 30, inclusive.
    Default: 7
    Description: Frequency (in days between 1 and 30, default is 7) to check organizational compliance by invoking the Lambda Function.
    MinValue: 1
    MaxValue: 30
    Type: Number
Resources:
  LaceworkControlTowerCfn:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${pSRASourceS3BucketName}.s3.${pSRAS3BucketRegion}.${AWS::URLSuffix}/${pSRAStagingS3KeyPrefix}/submodules/lacework-control-tower-cfn/templates/cfn-abi-control-tower-integration.template.yaml"
      Parameters:
        S3BucketName: !Ref pSRASourceS3BucketName
        S3KeyPrefix: !Ref pSRAStagingS3KeyPrefix
        LaceworkURL: !Ref LaceworkURL
        LaceworkOrgSubAccountNames: !Ref LaceworkOrgSubAccountNames
        LaceworkSubAccountName: !Ref LaceworkSubAccountName
        LaceworkAccessKeyID: !Ref LaceworkAccessKeyID
        LaceworkSecretKey: !Ref LaceworkSecretKey
        CapabilityType: !Ref CapabilityType
        ExistingAccounts: !Ref ExistingAccounts
        ExistingCloudTrail: !Ref ExistingCloudTrail
        LogAccountName: !Ref LogAccountName
        AuditAccountName: !Ref AuditAccountName
        KMSKeyIdentifierARN: !Ref KMSKeyIdentifierARN
  CfnAbiAwsSecurityHub:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub "https://${pSRASourceS3BucketName}.s3.${pSRAS3BucketRegion}.${AWS::URLSuffix}/${pSRAStagingS3KeyPrefix}/submodules/aws-security-reference-architecture-examples/aws_sra_examples/modules/securityhub-org-module/templates/sra-securityhub-org-module-main.yaml"
      Parameters:
        pRepoURL: !Ref pRepoURL
        pRepoBranch: !Ref pRepoBranch
        pCISStandardVersion: !Ref pCISStandardVersion
        pComplianceFrequency: !Ref pComplianceFrequency
        pCreateLambdaLogGroup: !Ref pCreateLambdaLogGroup
        pDisableSecurityHub: !Ref pDisableSecurityHub
        pEnableCISStandard: !Ref pEnableCISStandard
        pEnablePCIStandard: !Ref pEnablePCIStandard
        pEnableSecurityBestPracticesStandard: !Ref pEnableSecurityBestPracticesStandard
        pLambdaLogGroupKmsKey: !Ref pLambdaLogGroupKmsKey
        pLambdaLogGroupRetention: !Ref pLambdaLogGroupRetention
        pLambdaLogLevel: !Ref pLambdaLogLevel
        pRegionLinkingMode: !Ref pRegionLinkingMode
        pSRAAlarmEmail: !Ref pSRAAlarmEmail
      Tags:
        - Key: sra-solution
          Value: !Ref pSRAStagingS3KeyPrefix
  CfnAbiAmazonGuardDuty:
    Type: AWS::CloudFormation::Stack
    DependsOn:
         - "CfnAbiAwsSecurityHub"
    Properties:
      TemplateURL: !Sub "https://${pSRASourceS3BucketName}.s3.${pSRAS3BucketRegion}.${AWS::URLSuffix}/${pSRAStagingS3KeyPrefix}/submodules/aws-security-reference-architecture-examples/aws_sra_examples/modules/guardduty-org-module/templates/sra-guardduty-org-module-main.yaml"
      Parameters:
        pRepoURL: !Ref pRepoURL
        pRepoBranch: !Ref pRepoBranch
        pDisableGuardDuty: !Ref pDisableGuardDuty
        pAutoEnableS3Logs: !Ref pAutoEnableS3Logs
        pAutoEnableKubernetesAuditLogs: !Ref pAutoEnableKubernetesAuditLogs
        pAutoEnableMalwareProtection: !Ref pAutoEnableMalwareProtection
        pEnableRdsLoginEvents: !Ref pEnableRdsLoginEvents
        pEnableEksRuntimeMonitoring: !Ref pEnableEksRuntimeMonitoring
        pEnableEksAddonManagement: !Ref pEnableEksAddonManagement
        pEnableLambdaNetworkLogs: !Ref pEnableLambdaNetworkLogs
        pGuardDutyFindingPublishingFrequency: !Ref pGuardDutyFindingPublishingFrequency
        pSRAAlarmEmail: !Ref pSRAAlarmEmail
      Tags:
        - Key: sra-solution
          Value: !Ref pSRAStagingS3KeyPrefix
  LaceworkSecurityHubCfn:
    Type: AWS::CloudFormation::Stack
    DependsOn:
      - LaceworkControlTowerCfn
      - CfnAbiAwsSecurityHub
      - CfnAbiAmazonGuardDuty
    Properties:
      TemplateURL: !Sub "https://${pSRASourceS3BucketName}.s3.${pSRAS3BucketRegion}.${AWS::URLSuffix}/${pSRAStagingS3KeyPrefix}/templates/cfn-abi-lacework-sec-hub-ingest.template.yaml"
      Parameters:
        LaceworkAccount: !Select [ 0, !Split [ '.', !Ref LaceworkURL ] ]
        ExternalID: !Select [ 4, !Split [ '-', !Select [ 2, !Split [ '/', !Ref AWS::StackId ] ] ] ]
        ApiToken: "{{resolve:secretsmanager:LaceworkApiCredentials:SecretString:AccessToken}}"